apiVersion: ignite.weave.works/v1alpha3
kind: VM
metadata:
  name: smoke-test
  uid: $(uuidgen)
spec:
  cpus: 2
  diskSize: 4GB
  memory: 1GB
  image:
    oci:
      ref: weaveworks/ignite-ubuntu
  ssh: true
status:
  state: Created
